name: Master

on:
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - name: 👌🏻 Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        uses: actions/setup-go@v5
        with:
          go-version: "1.27"
      - name: 🔎 Run tests
        run: go test ./... -count=1 -covermode=count -coverprofile=coverage.out
      - name: Run unit tests
        run: go test ./tests/unit/... -count=1
